name: Super Fast Mega Extractor

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install MEGA-CMD (Official Stable)
      run: |
        sudo apt-get update
        sudo apt-get install -y curl libc6 libglib2.0-0 libicu-dev libssl-dev
        curl -o megacmd.deb https://mega.nz/linux/repo/Debian_11/amd64/megacmd-Debian_11_amd64.deb
        sudo apt-get install -y ./megacmd.deb
        # Force starting the mega service in background right now
        mega-cmd-server > /dev/null 2>&1 &
        sleep 5

    - name: Install Pyrogram & Crypto Core
      run: |
        pip install --no-cache-dir pyrogram tgcrypto

    - name: Run Bot Server
      env:
        API_ID: ${{ secrets.API_ID }}
        API_HASH: ${{ secrets.API_HASH }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        ADMIN_ID: ${{ secrets.ADMIN_ID }}
      run: python app.py
      
